### ISSUE TITLE
Badges at the release notes point to another plugin

### ISSUE THREAD

**Issue by mudrd8mz** [cwarwicker/moodle-tool_ribbons#3]
The badges at the top of the release notes for the latest version link to another plugin of yours.

Also, this type of badges might better fit into the plugin description (displayed at the front page) rather than release notes.

![image](https://user-images.githubusercontent.com/85831/106893884-7f5d4280-66ee-11eb-930e-d4d3ab2501fb.png)

**Comment by cwarwicker** [comment]
Oh whoops. I've changed them in the readme file and will change the description on moodle.org once you're happy with everything and I create a v1 release tag.

**Comment by mudrd8mz** [comment]
Well, the plugin has been approved. Further updates do not need further approvals so it's all in your hands now.
