### ISSUE TITLE
Environment Ribbons - Right-to-left user interface bug

### ISSUE THREAD

**Issue by acquaalta** [cwarwicker/moodle-tool_ribbons#4]
Hi,
We really really love this plugin, since it's so simple and effective and catches the attention of the user without taking too much visual space. However, we discovered that in an Right-to-Left (RTL) user interface, the ribbons are shown incorrectly. Their position is changed as expected from right to left or vice versa, but their angle stays the same, and the final result seems incorrect. 

I assume that if you would add a mechanism that flip the ribbon horizontally when changing the user interface of Moodle from right to left or vice versa, that would solve the issue.

Is it something that can be done? I hope so :-)

Please see the attached screenshot.

![Environment Ribbonms - RTL UI bug](https://user-images.githubusercontent.com/51836675/158078883-3230e2ac-b648-487a-a402-d181c95a85af.jpg)

**Comment by Uriel-Cerem-Devlion** [comment]
Hi everyone, 

We, in [Devlion co.](https://devlion.co.il/) in collaboration with [Tipli](https://www.tipli.info/) did some dev to solve that issue, and fixed that bug for the good use of RTL users and developers. 
For the solution, please see it in our commit 9ff210255abd316ae4467e45b0d85cdead4a9572. 
We  will appreciate notes and insights about our solution.

**Comment by cwarwicker** [comment]
Thanks, I've merged in the changes to fix the RTL issue.

**Comment by acquaalta** [comment]
Hi,
I'm a little bit confused. After installing the latest version of the plugin, the RTL behavior seems to be correct.
However, the latest version of the plugin is v1.0.3 (2021020402), which suggest that the code is only updated to 2021, while the fix for the issue is from 2022. Is it safe to assume that the fix is indeed included in the latest version of the plugin?

Thanks :-)
