### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [cwarwicker/moodle-tool_ribbons#6]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by cwarwicker** [comment]
I've added a new release version on moodle plugins db now which supports moodle 4.

https://moodle.org/plugins/tool_ribbons/versions

**Comment by acquaalta** [comment]
Thanks :-)
