### ISSUE TITLE
Environment Ribbons - Hyperlink value is not saved in the ribbon settings

### ISSUE THREAD

**Issue by acquaalta** [cwarwicker/moodle-tool_ribbons#7]
Hi,

Moodle version: 4.3.3
Plugin version: v1.0 (2021020400)

When creating a new ribbon, inserting a value in the "Hyperlink" field and saving, the hyperlink functions correctly in the ribbon itself. However, it seems that the value is not saved in the settings of the ribbon. 
It seems like a bug. Can it be fixed?

Thanks :-)

**Comment by cwarwicker** [comment]
This should be fixed now

**Comment by acquaalta** [comment]
Hi,
After installing the latest version, the bug seems to be fixed. Thanks :-)
